apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: "${APP_NAME}-template"
  app: "${APP_NAME}"
metadata:
  name: "${APP_NAME}-template"
parameters:
  - name: APP_NAME
    description: Application name
    value: sris
  - name: TAG
    description: The identifying tag for this specific deployment
    required: true
  - name: NAMESPACE
    description: Target namespace reference (i.e. 'k8vopl-dev')
    required: true

  - name: CHEFS_MAIL_FORM_ID
    description: Mail Form ID
    required: true
  - name: CHEFS_MAIL_FORM_VERSION
    description: Mail Form version number
    required: true
  - name: RCV_LAYER_ID
    description:
    required: true
  - name: CHES_URL
    description: The email service url
    required: true
  - name: CHEFS_MAIL_API_KEY
    description: The API key for email form
    required: true
  - name: SRC_LAYER_ID
    description: The source layer ID
    required: true
  - name: HV_CSV_ID
    description: High Volume CSV ID
    required: true
  - name: WEB_MAP_APP_ID
    description: Web Map App ID
    required: true
  - name: CHES_API_OAUTH_SECRET
    description: secret to connect to email api.
    required: true
  - name: RCV_CSV_ID
    description: Rcv csv id
    required: true
  - name: SRC_CSV_ID
    description: Application name
    required: true
  - name: MAPHUB_USER
    description: MapHub User
    required: true
  - name: CHEFS_HV_FORM_ID
    description: High Volume  Form ID.
    required: true
  - name: CHEFS_HV_FORM_VERSION
    description: High Volume  Form version number.
    required: true
  - name: MAPHUB_PASS
    description: map hub password.
    required: true
  - name: CHEFS_API_URL
    description: Chefs API URL
    required: true
  - name: AUTH_URL
    description: Authorization url.
    required: true
  - name: CHEFS_SOILS_FORM_ID
    description: Soil Form ID.
    required: true
  - name: CHEFS_SOILS_FORM_VERSION
    description: Soil Form version number.
    required: true
  - name: HV_LAYER_ID
    description: High Volume Layer ID.
    required: true
  - name: CHEFS_HV_API_KEY
    description: High Volume API key.
    required: true
  - name: CHEFS_SOILS_API_KEY
    description: Soils API Key
    required: true
  - name: LOGLEVEL
    description: Logging level
    required: true
  - name: NOTICE_STANDARD_TIME
    description: Notification processing interval time
    required: true
  - name: AGOL_UPDATE_FLAG
    description: FLAG to control, whether AGOL should be updated or not.
    required: true
  - name: EMAIL_NOTIFY_FLAG
    description: FLAG to control, retrieval of subscribers from CHEFs and notifying them via CHES.
    required: true
  - name: TIMEOUT_SECONDS
    description: Timeout to AGOL API call
    required: true
  - name: CHEFS_FORM_TIMEOUT_SECONDS
    description: Timeout to CHEFS API call to get form data
    required: true
  - name: CHES_EMAIL_TIMEOUT_SECONDS
    description: Timeout to CHES API call to send email
    required: true
  - name: CHES_TOKEN_TIMEOUT_SECONDS
    description: Timeout to CHES API call to get token
    required: true
  - name: CHES_HEALTH_TIMEOUT_SECONDS
    description: Timeout to CHES API call to check the health of API
    required: true
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-configmap
      labels:
        app: ${APP_NAME}
    data:
      CHEFS_MAIL_FORM_ID: ${CHEFS_MAIL_FORM_ID}
      CHEFS_MAIL_FORM_VERSION: ${CHEFS_MAIL_FORM_VERSION}
      RCV_LAYER_ID: ${RCV_LAYER_ID}
      CHES_URL: ${CHES_URL}
      CHEFS_MAIL_API_KEY: ${CHEFS_MAIL_API_KEY}
      SRC_LAYER_ID: ${SRC_LAYER_ID}
      HV_CSV_ID: ${HV_CSV_ID}
      WEB_MAP_APP_ID: ${WEB_MAP_APP_ID}
      CHES_API_OAUTH_SECRET: ${CHES_API_OAUTH_SECRET}
      RCV_CSV_ID: ${RCV_CSV_ID}
      SRC_CSV_ID: ${SRC_CSV_ID}
      MAPHUB_USER: ${MAPHUB_USER}
      CHEFS_HV_FORM_ID: ${CHEFS_HV_FORM_ID}
      CHEFS_HV_FORM_VERSION: ${CHEFS_HV_FORM_VERSION}
      MAPHUB_PASS: ${MAPHUB_PASS}
      CHEFS_API_URL: ${CHEFS_API_URL}
      AUTH_URL: ${AUTH_URL}
      CHEFS_SOILS_FORM_ID: ${CHEFS_SOILS_FORM_ID}
      CHEFS_SOILS_FORM_VERSION: ${CHEFS_SOILS_FORM_VERSION}
      HV_LAYER_ID: ${HV_LAYER_ID}
      CHEFS_HV_API_KEY: ${CHEFS_HV_API_KEY}
      CHEFS_SOILS_API_KEY: ${CHEFS_SOILS_API_KEY}
      LOGLEVEL: ${LOGLEVEL}
      NOTICE_STANDARD_TIME: ${NOTICE_STANDARD_TIME}
      AGOL_UPDATE_FLAG: ${AGOL_UPDATE_FLAG}
      EMAIL_NOTIFY_FLAG: ${EMAIL_NOTIFY_FLAG}
      TIMEOUT_SECONDS: ${TIMEOUT_SECONDS}
      CHEFS_FORM_TIMEOUT_SECONDS: ${CHEFS_FORM_TIMEOUT_SECONDS}
      CHES_EMAIL_TIMEOUT_SECONDS: ${CHES_EMAIL_TIMEOUT_SECONDS}
      CHES_TOKEN_TIMEOUT_SECONDS: ${CHES_TOKEN_TIMEOUT_SECONDS}
      CHES_HEALTH_TIMEOUT_SECONDS: ${CHES_HEALTH_TIMEOUT_SECONDS}

  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: "${APP_NAME}-cron-job"
    spec:
      schedule: "0 8 * * *"
      concurrencyPolicy: "Replace"
      startingDeadlineSeconds: 300
      suspend: false
      successfulJobsHistoryLimit: 30
      failedJobsHistoryLimit: 30
      jobTemplate:
        spec:
          activeDeadlineSeconds: 1800
          template:
            metadata:
              labels:
                app: "${APP_NAME}"
            spec:
              containers:
                - name: "${APP_NAME}-job"
                  image: ghcr.io/bcgov/nr-soils-relocation/${APP_NAME}:${TAG}
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "2Gi"
                    limits:
                      cpu: "1.45"
                      memory: "3.9Gi"
                  envFrom:
                    - configMapRef:
                        name: "${APP_NAME}-configmap"
              restartPolicy: OnFailure


