name: Build And Add Job to Openshift
env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE_NO_ENV: ${{ secrets.NAMESPACE_NO_ENV}}
  CHEFS_SOILS_FORM_ID: ${{ secrets.CHEFS_SOILS_FORM_ID }}
  CHEFS_SOILS_API_KEY: ${{ secrets.CHEFS_SOILS_API_KEY }}
  CHEFS_HV_FORM_ID: ${{ secrets.CHEFS_HV_FORM_ID }}
  CHEFS_HV_API_KEY: ${{ secrets.CHEFS_HV_API_KEY }}
  CHEFS_MAIL_FORM_ID: ${{ secrets.CHEFS_MAIL_FORM_ID }}
  CHEFS_MAIL_API_KEY: ${{ secrets.CHEFS_MAIL_API_KEY }}
  CHES_API_KEY: ${{ secrets.CHES_API_KEY }}
  MAPHUB_USER: ${{ secrets.MAPHUB_USER }}
  MAPHUB_PASS: ${{ secrets.MAPHUB_PASS }}
  APP_NAME: "SRIS"
on:
  workflow_dispatch:

jobs:
  Build_Deploy:
    name: Build and deploy to OpenShift
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to GitHub runner.
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4.10
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set +e -ux
          # Login to OpenShift and select project
          oc login --token=${{ env.OPENSHIFT_TOKEN }} --server=${{ env.OPENSHIFT_SERVER }}
          oc create configmap ${{ env.APP_NAME }}"-config-map --from-literal=CHEFS_SOILS_FORM_ID=${{ env.CHEFS_SOILS_FORM_ID }} --from-literal=CHEFS_SOILS_API_KEY=${{ env.CHEFS_SOILS_API_KEY }} --from-literal=CHEFS_HV_FORM_ID=${{ env.CHEFS_HV_FORM_ID }} --from-literal=CHEFS_HV_API_KEY=${{ env.CHEFS_HV_API_KEY }} --from-literal=CHEFS_MAIL_FORM_ID=${{ env.CHEFS_MAIL_FORM_ID }} --from-literal=CHEFS_MAIL_API_KEY=${{ env.CHEFS_MAIL_API_KEY }} --from-literal=CHES_API_KEY=${{ env.CHES_API_KEY }} --from-literal=MAPHUB_USER=${{ env.MAPHUB_USER }} --from-literal=MAPHUB_PASS=${{ env.MAPHUB_PASS }} --dry-run -o yaml \
          | oc apply -f -
