name: Execute the SRIS CHEFS load script
on:
  workflow_dispatch:

  schedule:
    # * is a special character in YAML, so you have to quote this string
    # Execute at 1:00am every day
    - cron:  '0 1 * * *'
jobs:
  SRIS_CHEFS_LOAD:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to GitHub runner.
        with:
          ref: deploy/prod # Specify the branch to checkout.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.12 #install the python version needed
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"   
      - name: install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel        
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}          
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev          
      - name: execute the python script
        env:
          CHEFS_SOILS_FORM_ID: ${{ secrets.CHEFS_SOILS_FORM_ID }}
          CHEFS_SOILS_API_KEY: ${{ secrets.CHEFS_SOILS_API_KEY }}
          CHEFS_HV_FORM_ID: ${{ secrets.CHEFS_HV_FORM_ID }}
          CHEFS_HV_API_KEY: ${{ secrets.CHEFS_HV_API_KEY }}
          CHEFS_MAIL_FORM_ID: ${{ secrets.CHEFS_MAIL_FORM_ID }}
          CHEFS_MAIL_API_KEY: ${{ secrets.CHEFS_MAIL_API_KEY }}
          CHES_API_KEY: ${{ secrets.CHES_API_KEY }}
          MAPHUB_USER: ${{ secrets.MAPHUB_USER }}
          MAPHUB_PASS: ${{ secrets.MAPHUB_PASS }}
        run: |
          pipenv run python chefs_soils.py
